"""User_new_att_2

Revision ID: 207cce6b4b32
Revises: 44515960b06b
Create Date: 2024-06-19 15:50:55.059940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '207cce6b4b32'
down_revision: Union[str, None] = '44515960b06b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chat_id', sa.String(length=150), nullable=True))
    op.create_unique_constraint(None, 'users', ['chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'chat_id')
    # ### end Alembic commands ###
