"""User_new_att

Revision ID: 44515960b06b
Revises: eb7598f31ddb
Create Date: 2024-06-14 22:42:21.948409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44515960b06b'
down_revision: Union[str, None] = 'eb7598f31ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('parking_expenses_limit', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'parking_expenses_limit')
    # ### end Alembic commands ###
