"""Chat_id_unique_false

Revision ID: 90c60ceb3d90
Revises: 9615850ff351
Create Date: 2024-06-21 12:37:28.266878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c60ceb3d90'
down_revision: Union[str, None] = '9615850ff351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_chat_id_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_chat_id_key', 'users', ['chat_id'])
    # ### end Alembic commands ###
