"""TToken

Revision ID: 9615850ff351
Revises: 207cce6b4b32
Create Date: 2024-06-21 10:43:33.457305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9615850ff351'
down_revision: Union[str, None] = '207cce6b4b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_token', sa.String(length=150), nullable=True))
    op.create_unique_constraint(None, 'users', ['telegram_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'telegram_token')
    # ### end Alembic commands ###
